apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-db
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-db
  template:
    metadata:
      labels:
        app: order-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ORDER_DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: ORDER_DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: ORDER_DB_PASS
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: order-db-data
      volumes:
        - name: order-db-data
          persistentVolumeClaim:
            claimName: order-db-pvc
