apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: microservices
type: Opaque
stringData:
  # General
  JWT_SECRET: "123456"

  # RabbitMQ
  RABBITMQ_USER: "guest"
  RABBITMQ_PASS: "guest"

  # Order Service DB
  ORDER_DB_USER: "postgres"
  ORDER_DB_PASS: "123456"

  # Payment Service DB
  PAYMENT_DB_USER: "postgres"
  PAYMENT_DB_PASS: "123456"

  # Notification / SMTP
  SMTP_USER: "guest"
  SMTP_PASS: "guest"
  SMTP_FROM: "Shop Support <support@myshop.com>"
